-- MySQL Script generated by MySQL Workbench
-- Sat Sep 26 16:55:12 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `password` VARCHAR(70) NOT NULL,
  `telefono` VARCHAR(30) NULL,
  `calle` VARCHAR(45) NULL,
  `numero` INT NULL,
  `dpto` VARCHAR(10) NULL,
  `cp` VARCHAR(15) NULL,
  `provincia` VARCHAR(45) NULL,
  `localidad` VARCHAR(45) NULL,
  `rol` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Subcategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Subcategories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `categoria_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `categoria_idx` (`categoria_id` ASC),
  CONSTRAINT `categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `mydb`.`Categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` INT NOT NULL,
  `descuento` INT NULL,
  `descripcion` VARCHAR(45) NULL,
  `subcategoria_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `subcategory_idx` (`subcategoria_id` ASC),
  CONSTRAINT `subcategory`
    FOREIGN KEY (`subcategoria_id`)
    REFERENCES `mydb`.`Subcategories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product_images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `producto_id` INT NULL,
  `imagen` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `producto_id_idx` (`producto_id` ASC),
  CONSTRAINT `producto_id`
    FOREIGN KEY (`producto_id`)
    REFERENCES `mydb`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuario_id_carrito_idx` (`usuario_id` ASC),
  CONSTRAINT `usuario_id_carrito`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cart_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cart_products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `carrito_id` INT NULL,
  `producto_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `carrito_id_idx` (`carrito_id` ASC),
  INDEX `producto_id_carrito_idx` (`producto_id` ASC),
  CONSTRAINT `carrito_id`
    FOREIGN KEY (`carrito_id`)
    REFERENCES `mydb`.`cart` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `producto_id_carrito`
    FOREIGN KEY (`producto_id`)
    REFERENCES `mydb`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`compra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuario_id_compra_idx` (`usuario_id` ASC),
  CONSTRAINT `usuario_id_compra`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`compra_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`compra_products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `compra_id` INT NULL,
  `producto_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `compra_id_idx` (`compra_id` ASC),
  INDEX `producto_id_compra_idx` (`producto_id` ASC),
  CONSTRAINT `compra_id`
    FOREIGN KEY (`compra_id`)
    REFERENCES `mydb`.`compra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `producto_id_compra`
    FOREIGN KEY (`producto_id`)
    REFERENCES `mydb`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
